<!-- @@DAL_SP@@ -->

USE [@@DB_NAME@@]
GO

DROP PROCEDURE @@SP_NAME@@
GO

CREATE PROCEDURE @@SP_NAME@@
	@@SP_PARAMS@@
AS
BEGIN



IF (IDENT_CURRENT('@@TABLE_NAME@@') IS NOT NULL) 
	BEGIN
		INSERT 
			INTO @@TABLE_NAME@@ (
				@@INSERT_FIELD_NAMES_WITHOUT_PKFIELD@@
			)
			VALUES (
				@@INSERT_FIELD_VALUES_WITHOUT_PKFIELD@@
			);
			SELECT CAST (SCOPE_IDENTITY() AS @@TABLE_PKFIELD_DBTYPE@@)AS PKFIELD;
	END
ELSE
	BEGIN
		INSERT 
			INTO @@TABLE_NAME@@ (
				@@INSERT_FIELD_NAMES@@
			)
			VALUES (
				@@INSERT_FIELD_VALUES@@
			);
			
			SELECT @@TABLE_PKFIELD_PARAMNAME@@ AS PKFIELD;
	END
END
GO


<!-- @@DAL_SP@@ -->