<!-- @@DAL_SP@@ -->

USE [@@DB_NAME@@]
GO

DROP PROCEDURE @@SP_NAME@@
GO

CREATE PROCEDURE @@SP_NAME@@
    @@TABLE_PKFIELD_PARAMNAME@@  @@TABLE_PKFIELD_TYPE@@
AS
BEGIN
	DELETE FROM @@TABLE_NAME@@
	WHERE @@TABLE_PKFIELD_NAME@@ = @@TABLE_PKFIELD_PARAMNAME@@
END
GO

<!-- @@DAL_SP@@ -->